### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#136]
```
The Twitter app works perfectly most of the time. Occasionally i get this
error though:

Traceback (most recent call last):

  File "/usr/lib/python2.4/site-packages/django/core/handlers/base.py",
line 92, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/usr/lib/python2.4/site-packages/django/views/generic/simple.py",
line 16, in direct_to_template
    c = RequestContext(request, dictionary)

  File "/usr/lib/python2.4/site-packages/django/template/context.py", line
107, in __init__
    self.update(processor(request))

  File "/home/myserver/django/myserver/verkoop/context_processors.py", line
13, in latest_tweet
    tweet = twitter.Api().GetUserTimeline( settings.TWITTER_USER, count=5 )

  File "build/bdist.linux-x86_64/egg/twitter.py", line 1414, in GetUserTimeline

  File "build/bdist.linux-x86_64/egg/twitter.py", line 2032, in _FetchUrl

  File "/usr/lib64/python2.4/urllib2.py", line 358, in open
    response = self._open(req, data)

  File "/usr/lib64/python2.4/urllib2.py", line 376, in _open
    '_open', req)

  File "/usr/lib64/python2.4/urllib2.py", line 337, in _call_chain
    result = func(*args)

  File "/usr/lib64/python2.4/urllib2.py", line 1032, in http_open
    return self.do_open(httplib.HTTPConnection, req)

  File "/usr/lib64/python2.4/urllib2.py", line 1006, in do_open
    raise URLError(err)

URLError: <urlopen error (104, 'Connection reset by peer')>

Any idea how i prevent this?
```

Original issue reported on code.google.com by `het.oos...@gmail.com` on 13 Apr 2010 at 12:56

**Comment by GoogleCodeExporter** [comment]
```
Does this have something to do with this issue:
http://code.google.com/p/python-twitter/issues/detail?id=92


```

Original comment by `het.oos...@gmail.com` on 19 Apr 2010 at 8:19
