### ISSUE TITLE
Doesn't support Twitter's mandatory oauth

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#170]
```
>>> import twitter
>>> a = twitter.Api(username='*******',password='******')
>>> a.GetPublicTimeline()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/pymodules/python2.6/twitter.py", line 1319, in GetPublicTimelin
e
    json = self._FetchUrl(url,  parameters=parameters)
  File "/usr/lib/pymodules/python2.6/twitter.py", line 2030, in _FetchUrl
    url_data = opener.open(url, encoded_post_data).read()
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized
>>> 

```

Original issue reported on code.google.com by `lgp171...@gmail.com` on 8 Oct 2010 at 5:28
- Merged into: #65

**Comment by GoogleCodeExporter** [comment]
```
marking as a dupe of issue 65

oauth support is present in the tip of the default branch, I just need to do a 
freaking release! :)

```

Original comment by `bear42` on 8 Oct 2010 at 6:13
- Changed state: **Duplicate**
