### ISSUE TITLE
I can't install simplejson

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#188]
```
What steps will reproduce the problem?
1. I am tring to use the twitter-python API
2. I download simplejson-2.1.3 
3. I tried to run setup.py and I got this error message:
Traceback (most recent call last):
  File "C:\Python27\simplejson-2.1.3\setup.py", line 103, in <module>
    run_setup(True)
  File "C:\Python27\simplejson-2.1.3\setup.py", line 99, in run_setup
    cmdclass={'build_ext': ve_build_ext},
  File "C:\Python27\lib\distutils\core.py", line 140, in setup
    raise SystemExit, gen_usage(dist.script_name) + "\nerror: %s" % msg
SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] 
...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

What is the expected output? What do you see instead?
I see the error message above

What version of the product are you using? On what operating system?
I am using Python 2.7

Please provide any additional information below.

Please help me, Thank you all
```

Original issue reported on code.google.com by `maayan1...@gmail.com` on 5 Mar 2011 at 10:16

**Comment by GoogleCodeExporter** [comment]
```
you need to run this:

python setup.py install

without the "install" keyword it won't do anything (which it was trying to tell 
you in the output)
```

Original comment by `bear42` on 16 Apr 2011 at 11:04
- Changed state: **Invalid**
