### ISSUE TITLE
Missing twitter_pb2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#199]
```
-What steps will reproduce the problem?
   $ hg clone http://python-twitter.googlecode.com/hg/ python-twitter
   $ cd python-twitter
   $ hg update dev


-What is the expected output? 
   $python examples/tweet.py 
Usage: tweet [options] message
....


-What do you see instead?
   $ python examples/tweet.py 
Traceback (most recent call last):
  File "examples/tweet.py", line 11, in <module>
    import twitter
  File "/usr/local/lib/python2.6/dist-packages/python_twitter-0.6_devel-py2.6.egg/twitter.py", line 38, in <module>
    import twitter_pb2
ImportError: No module named twitter_pb2



-What version of the product are you using? On what operating system?
   dev branch on jun 17.
   Ubuntu 10.04.2 LTS
   Python 2.6.5


Please provide any additional information below.
  - Fix : sudo cp twitter_pb2.py /usr/local/lib/python2.6/dist-packages/python_twitter-0.6_devel-py2.6.egg/

```

Original issue reported on code.google.com by `yohannle...@2xyo.info` on 17 Jun 2011 at 5:19

**Comment by GoogleCodeExporter** [comment]
```
That branch is a work-in-progress and is not guaranteed to be working or even 
updated - the dev who is doing the work is not active anymore and we have 
focused our work in keeping the trunk functional.  I personally have no 
experience with that branch so could not even begin to point you to where the 
pb2 file is.

marking this as WontFix 
```

Original comment by `bear42` on 19 Jun 2011 at 9:01
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
The file twitter_pb2.py is in  python-twitter directory :
http://code.google.com/p/python-twitter/source/browse/?name=dev 

Thanks
```

Original comment by `yohannle...@2xyo.info` on 20 Jun 2011 at 6:57
