### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#242]
```
What steps will reproduce the problem?
1. Authorize in api:
api = twitter.Api(consumer_key, consumer_secret, access_token, 
access_token_secret)
2. Get public timeline:
statuses = api.GetPublicTimeline()

What is the expected output? What do you see instead?
Expected statuses, instead i got errror:

Traceback (most recent call last):
  File "C:\workspace\twitter\tt_tmp.py", line 9, in <module>
    statuses = api.GetPublicTimeline()
  File "build\bdist.win32\egg\twitter.py", line 2301, in GetPublicTimeline
  File "build\bdist.win32\egg\twitter.py", line 620, in NewFromJsonDict
AttributeError: 'unicode' object has no attribute 'get'

What version of the product are you using? On what operating system?
python-twitter 0.8.2, Python 2.7 on Win7 64bit

Please provide any additional information below.
GetUserTimeline works fine.

```

Original issue reported on code.google.com by `Bartosz....@gmail.com` on 26 Oct 2012 at 12:19

**Comment by GoogleCodeExporter** [comment]
```
Problem is in old api version. Python-twitter uses api 1.0 but now in current 
api 1.1 some functions are deprecated and returns u"error" instead of expected 
values.

```

Original comment by `Bartosz....@gmail.com` on 26 Oct 2012 at 6:24
