### ISSUE TITLE
Pip Install from source fails (google code)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#249]
```
What steps will reproduce the problem?
1. pip install -e hg+http://python-twitter.googlecode.com/hg#egg=twitter


Expected the package to install without issue, as it has done for months.


Am pointing towards the latest source.


There is an error in setup.py due as it is looking for the README.md file, 
which does not seem to exist in this repository, but just so happens to exist 
on Github.

I point to this repo's source, given it is supposed to be the "source of truth".

This fix would be a quick win!
```

Original issue reported on code.google.com by `defb...@gmail.com` on 20 Feb 2013 at 6:19

**Comment by GoogleCodeExporter** [comment]
```
Obtaining twitter from hg+http://python-twitter.googlecode.com/hg#egg=twitter
  Updating ./src/twitter clone
  Running setup.py egg_info for package twitter
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/var/www/src/twitter/setup.py", line 73, in <module>
        Main()
      File "/var/www/src/twitter/setup.py", line 60, in Main
        METADATA['long_description'] = BuildLongDescription()
      File "/var/www/src/twitter/setup.py", line 56, in BuildLongDescription
        return '\n'.join([Read('README.md'), Read('CHANGES')])
      File "/var/www/src/twitter/setup.py", line 53, in Read
        return open(file).read()
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/var/www/src/twitter/setup.py", line 73, in <module>

    Main()

  File "/var/www/src/twitter/setup.py", line 60, in Main

    METADATA['long_description'] = BuildLongDescription()

  File "/var/www/src/twitter/setup.py", line 56, in BuildLongDescription

    return '\n'.join([Read('README.md'), Read('CHANGES')])

  File "/var/www/src/twitter/setup.py", line 53, in Read

    return open(file).read()

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in 
/var/www/src/twitter

```

Original comment by `defb...@gmail.com` on 20 Feb 2013 at 6:20

**Comment by GoogleCodeExporter** [comment]
```
same issue here
```

Original comment by `serge.ul...@gmail.com` on 5 Mar 2013 at 8:08

**Comment by GoogleCodeExporter** [comment]
```
fixed in latest version
```

Original comment by `bear42` on 6 Oct 2013 at 10:18
- Changed state: **Fixed**
