### ISSUE TITLE
GetUser gives a "page does not exist 34"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#256]
```
What steps will reproduce the problem?
 >>> import twitter
 >>> hej = twitter.Api(consumer_key=ck,consumer_secret=cs,access_token_key=atk, access_token_secret=ats)
 >>> user = hej.GetUser(user)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-1.0-py2.7.egg/twitter.py", line 3461, in GetUser
    data = self._ParseAndCheckTwitter(json)
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-1.0-py2.7.egg/twitter.py", line 4396, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-1.0-py2.7.egg/twitter.py", line 4421, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.TwitterError: [{u'message': u'Sorry, that page does not exist', 
u'code': 34}]


What is the expected output? What do you see instead?
I expect to get info about the user

What version of the product are you using? On what operating system?
xthojak@E4300:~$ uname -a
Linux E4300 3.2.0-45-generic #70-Ubuntu SMP Wed May 29 20:12:06 UTC 2013 x86_64 
x86_64 x86_64 GNU/Linux
>>> twitter.__version__
'1.0'

Please provide any additional information below.
Trying to get the number of followers but it seams like the way I did it a 
couple of months ago doesn't work anymore (GetUser(self.user).followers_count). 
Guess it is due to the new 1.1 API. I have updated to python-twitter 1.0, and 
for example getUserTimeline works. Tried to use GetFollowers and count instead 
as a workaround but run into some rate limiting
```

Original issue reported on code.google.com by `thom...@gmail.com` on 17 Jul 2013 at 7:53

**Comment by GoogleCodeExporter** [comment]
```
Hello, please use the user_id or screen_name kwargs of GetUser(). These are new 
in Twitter API 1.1.

Like:

GetUser(screen_name='example') or GetUser(user_id=123456)


```

Original comment by `sebastia...@gmail.com` on 25 Jul 2013 at 8:22
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
@duymtys my friend please fix it because now page doesn't exist so I need your 
help 

I miss my friend 
```

Original comment by `Johan.el...@gmail.com` on 4 Aug 2014 at 11:29
