### ISSUE TITLE
setup.py test - fails on AsJsonString methods

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#36]
```
What steps will reproduce the problem?
1. Install latest simplejson
   - setup.py build SUCCEEDS
   - setup.py install SUCCEEDS
   - setup.py test SUCCEEDS

2. Install latest python-twitter 
   - setup.py build SUCCEEDS
   - setup.py install SUCCEEDS
   - setup.py test FAILS (2)
      - FAIL: Test the twitter.User AsJsonString method
      - FAIL: Test the twitter.Status AsJsonString method

3. Try to use python-twitter. Example source code:
   import twitter
   api = twitter.Api()

What is the expected output? What do you see instead?
I'm aware that the above program would produce nothing, but I still get an
error from this:

Traceback (most recent call last):
  File "twitter.py", line 1, in <module>
    import twitter
  File "/home/sam/Documents/Programming/Python/twitter.py", line 2, in <module>
    api = twitter.Api()

What version of the product are you using? On what operating system?
simplejson 2.0.6
python-twitter 0.5
Ubuntu 8.0.4

Please provide any additional information below.
N/A
```

Original issue reported on code.google.com by `sam.starling` on 28 Dec 2008 at 11:59

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.  I believe the best solution will be to bundle a version 
of
simplejson with the python-twitter library.
```

Original comment by `dclinton` on 29 Dec 2008 at 12:05
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This is fixed in trunk.  Please test.
```

Original comment by `dclinton` on 21 Jan 2009 at 7:54
- Changed state: **Fixed**
