### ISSUE TITLE
Non ASCII characters causes exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#41]
```
What steps will reproduce the problem?
1. send an update string containing any non ascii character ( like ñ )
2. sample :
>>> text = "words with ñ"
>>> import twitter
>>> api=twitter.Api('c######','######')
>>> api.PostUpdate(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.5-i386/egg/twitter.py", line 1054, in PostUpdate
  File "build/bdist.macosx-10.5-i386/egg/twitter.py", line 1418, in _FetchUrl
  File "build/bdist.macosx-10.5-i386/egg/twitter.py", line 1391, in _EncodePostData
  File "build/bdist.macosx-10.5-i386/egg/twitter.py", line 1356, in _Encode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal 
not in range(128)


probando con la ñ
Traceback (most recent call last):
  File "twitminal.py", line 79, in <module>
    api.PostUpdate(text)
  File "build/bdist.macosx-10.5-i386/egg/twitter.py", line 1054, in PostUpdate
  File "build/bdist.macosx-10.5-i386/egg/twitter.py", line 1418, in _FetchUrl
  File "build/bdist.macosx-10.5-i386/egg/twitter.py", line 1391, in _EncodePostData
  File "build/bdist.macosx-10.5-i386/egg/twitter.py", line 1356, in _Encode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: 
ordinal not in 
range(128)


What is the expected output? What do you see instead?
This shouldnt be a problem to encode.

What version of the product are you using? On what operating system?
latest stable version, on Leopard.


```

Original issue reported on code.google.com by `cromest...@gmail.com` on 20 Feb 2009 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
check in which coding it's your output, but i added there this data =
simplejson.loads(json, 'iso8859-1') (because of default web server output). 
Reason
is, that you're not sending any of standard browser user-agent. if you'll send 
for
example mozilla, then your output will be in utf-8. use chardet for 
identifiacion
```

Original comment by `adse...@synopsi.com` on 20 Feb 2009 at 7:47

**Comment by GoogleCodeExporter** [comment]
```
you're right to suspect what the encoding is, its quite strange the output of 
chardet
first of all i m on a Leopard machine with all installed in english

now if I input abc just before PostUpdate i get this

abc
{'confidence': 1.0, 'encoding': 'ascii'}

if i input abcñ, i get this encoding

abcñ
{'confidence': 0.98999999999999999, 'encoding': 'EUC-JP'}
will investigate to see why this change is ocurring
```

Original comment by `cromest...@gmail.com` on 20 Feb 2009 at 7:59

**Comment by GoogleCodeExporter** [comment]
```
Forgot to state that this input is coming from std in, caught this way :

sys.stdin.readline()

```

Original comment by `cromest...@gmail.com` on 20 Feb 2009 at 8:00

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Ok, forget it, no issue, just set up third parameter in constructor and you're 
set.

sorry bout it.

rewrote the function and saw that there was a problem with that aprameter, and 
then finally saw i had to specify 
it.
sorry bout that, thanks for the lib, works great.
```

Original comment by `cromest...@gmail.com` on 21 Feb 2009 at 2:43

**Comment by GoogleCodeExporter** [comment]
```
Thanks for following up, cromestant.  I'm marking this Invalid but please feel 
free
to reopen if there are further related issues.
```

Original comment by `dclinton` on 21 Feb 2009 at 4:26
- Changed state: **Invalid**
