### ISSUE TITLE
Patch: allow count in GetFriendsTimeline()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#44]
```
The Twitter API supports an optional 'count' parameter, which "Specifies the 
number of statuses to 
retrieve. May not be greater than 200.":

http://apiwiki.twitter.com/REST+API+Documentation#friendstimeline

This patch adds the same parameter to python-twitter.
```

Original issue reported on code.google.com by `thomasdy...@gmail.com` on 3 Mar 2009 at 9:45

Attachments:
- [twitter-count.patch](https://storage.googleapis.com/google-code-attachments/python-twitter/issue-44/comment-0/twitter-count.patch)

**Comment by GoogleCodeExporter** [comment]
Original comment by `dclinton` on 3 Mar 2009 at 1:55
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Applied and slightly modified in r135:

  http://code.google.com/p/python-twitter/source/detail?r=135

Please test and verify.

```

Original comment by `dclinton` on 3 Mar 2009 at 2:10
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Looks good to me - see tests below. Thanks for applying this.

Tom

>>> len(api.GetFriendsTimeline(user, count=2))
2
>>> len(api.GetFriendsTimeline(user, count=20))
20
>>> len(api.GetFriendsTimeline(user, count=201))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "twitter.py", line 1354, in GetFriendsTimeline
    raise TwitterError("'count' may not be greater than 200")
twitter.TwitterError: 'count' may not be greater than 200
```

Original comment by `thomasdy...@gmail.com` on 3 Mar 2009 at 3:18
