### ISSUE TITLE
test suite fails on twitter.Status  getters and setters and twitter.Status properties

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#6]
```
When I run the test:

(shouldn't real comparison rather be "X within tolerance interval"?)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

[artm@salyangoz python-twitter-0.4]$ python twitter_test.py
/var/lib/python-support/python2.5/simplejson/scanner.py:6:
DeprecationWarning: The sre module is deprecated, please import re.
  from sre import VERBOSE, MULTILINE, DOTALL
........................F..F........
======================================================================
FAIL: Test all of the twitter.Status getters and setters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "twitter_test.py", line 53, in testGettersAndSetters
    self.assertEqual(1169882234, status.GetCreatedAtInSeconds())
AssertionError: 1169882234 != 1169849834.0

======================================================================
FAIL: Test all of the twitter.Status properties
----------------------------------------------------------------------
Traceback (most recent call last):
  File "twitter_test.py", line 69, in testProperties
    self.assertEqual(1169882234, status.created_at_in_seconds)
AssertionError: 1169882234 != 1169849834.0

----------------------------------------------------------------------
Ran 36 tests in 0.157s

FAILED (failures=2)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

```

Original issue reported on code.google.com by `femistofel@gmail.com` on 11 Sep 2007 at 8:43

**Comment by GoogleCodeExporter** [comment]
```
Interesting...  I wonder if this is a python 2.5 thing.  I'm only testing 
against 2.4.  Accepting.
```

Original comment by `dclinton` on 14 Sep 2007 at 4:25

**Comment by GoogleCodeExporter** [comment]
Original comment by `dclinton` on 15 Nov 2007 at 1:46
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
apparently it's fixed 
```

Original comment by `femistofel@gmail.com` on 16 May 2008 at 7:47

**Comment by GoogleCodeExporter** [comment]
```
Can't verify against trunk on either 2.4 or 2.5.  Closing.
```

Original comment by `dclinton` on 21 Jan 2009 at 7:46
- Changed state: **Invalid**
